export const UPDATE_FORM_VALUES = 'UPDATE_FORM_VALUES';
export const CHANGE_FORM_VALUES = 'CHANGE_FORM_VALUES';
export const DESTROY_FORM = 'DESTROY_FORM';
export const INITIALIZE_FORM_VALUES = 'INITIALIZE_FORM_VALUES';
