export const DEFAULT_SERIES_COLORS = {
  PURPLE_PASTEL: '#CF8FE5',
  BLACK_SMOKE: '#282828',
  WHITE_SEPIA: '#EEE7DF',
  COLD_ICE: '#8FA2E5',
  GRAY_MIDNIGHT: '#787878',
  PURPLE_SWEET: '#CF8FE5',
  GRAY_SURFACE: '#404040',
  HOLY_SKY: '#8FCBE5',
  SUNSET_ORANGE: '#FAC12B',
  SUMMER_GRASS: '#80B980',
  SKIN_AROMA: '#FFAD6F',
};

export const DEFAULT_SERIES_COLORS_SET = Object.values(DEFAULT_SERIES_COLORS);

export const CHART_ELEMENT_COLORS = {
  LABEL_BASE: '#282828',
};
