export { default as Footer } from './Footer';
export { default as Heading } from './Heading';
export { default as PaginatorLayout } from './PaginatorLayout';
export { default as PhoneInfo } from './PhoneInfo';
export { default as SideMenu } from './SideMenu';
export { default as SubHeadline } from './SubHeadline';
export { default as ExoticHeading } from './ExoticHeading';
export { default as Wrapper } from './Wrapper';
export { default as RightArrowLabel } from './RightArrowLabel';
