apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "labels" . | indent 4 }}
  name: {{ template "app.fullname" . }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  4096;
    }

    http {
      types {
          text/html                                        html htm shtml;
          text/css                                         css;
          text/xml                                         xml;
          image/gif                                        gif;
          image/jpeg                                       jpeg jpg;
          application/javascript                           js;
          application/atom+xml                             atom;
          application/rss+xml                              rss;

          text/mathml                                      mml;
          text/plain                                       txt;
          text/vnd.sun.j2me.app-descriptor                 jad;
          text/vnd.wap.wml                                 wml;
          text/x-component                                 htc;

          image/png                                        png;
          image/svg+xml                                    svg svgz;
          image/tiff                                       tif tiff;
          image/vnd.wap.wbmp                               wbmp;
          image/webp                                       webp;
          image/x-icon                                     ico;
          image/x-jng                                      jng;
          image/x-ms-bmp                                   bmp;

          font/woff                                        woff;
          font/woff2                                       woff2;

          application/java-archive                         jar war ear;
          application/json                                 json map;
          application/mac-binhex40                         hqx;
          application/msword                               doc;
          application/pdf                                  pdf;
          application/postscript                           ps eps ai;
          application/rtf                                  rtf;
          application/vnd.apple.mpegurl                    m3u8;
          application/vnd.google-earth.kml+xml             kml;
          application/vnd.google-earth.kmz                 kmz;
          application/vnd.ms-excel                         xls;
          application/vnd.ms-fontobject                    eot;
          application/vnd.ms-powerpoint                    ppt;
          application/vnd.oasis.opendocument.graphics      odg;
          application/vnd.oasis.opendocument.presentation  odp;
          application/vnd.oasis.opendocument.spreadsheet   ods;
          application/vnd.oasis.opendocument.text          odt;
          application/vnd.openxmlformats-officedocument.presentationml.presentation
                                                           pptx;
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                                                           xlsx;
          application/vnd.openxmlformats-officedocument.wordprocessingml.document
                                                           docx;
          application/vnd.wap.wmlc                         wmlc;
          application/x-7z-compressed                      7z;
          application/x-cocoa                              cco;
          application/x-java-archive-diff                  jardiff;
          application/x-java-jnlp-file                     jnlp;
          application/x-makeself                           run;
          application/x-perl                               pl pm;
          application/x-pilot                              prc pdb;
          application/x-rar-compressed                     rar;
          application/x-redhat-package-manager             rpm;
          application/x-sea                                sea;
          application/x-shockwave-flash                    swf;
          application/x-stuffit                            sit;
          application/x-tcl                                tcl tk;
          application/x-x509-ca-cert                       der pem crt;
          application/x-xpinstall                          xpi;
          application/xhtml+xml                            xhtml;
          application/xspf+xml                             xspf;
          application/zip                                  zip;

          application/octet-stream                         bin exe dll;
          application/octet-stream                         deb;
          application/octet-stream                         dmg;
          application/octet-stream                         iso img;
          application/octet-stream                         msi msp msm;

          audio/midi                                       mid midi kar;
          audio/mpeg                                       mp3;
          audio/ogg                                        ogg;
          audio/x-m4a                                      m4a;
          audio/x-realaudio                                ra;

          video/3gpp                                       3gpp 3gp;
          video/mp2t                                       ts;
          video/mp4                                        mp4;
          video/mpeg                                       mpeg mpg;
          video/quicktime                                  mov;
          video/webm                                       webm;
          video/x-flv                                      flv;
          video/x-m4v                                      m4v;
          video/x-mng                                      mng;
          video/x-ms-asf                                   asx asf;
          video/x-ms-wmv                                   wmv;
          video/x-msvideo                                  avi;
        }

        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        tcp_nopush     on;

        keepalive_timeout  30;

        gzip  off;

        # include /etc/nginx/conf.d/*.conf;

        map $http_origin $cors_header{
          default "";
          {{- range $v := .Values.nginxconf.corsregexp }}
          "{{ $v }}" "$http_origin";
          {{- end }}
        }

        server {
            listen   80 default_server;
            #server_name  testname.com;

            #charset koi8-r;
            access_log  /var/log/nginx/access.log  main;
            error_log  /var/log/nginx/error.log warn;

            location / {
                root {{ .Values.nginxconf.rootpath }};
                add_header cache-control "public, max-age=3600";
                add_header host-name $hostname always;
                try_files $uri $uri/ /;
                autoindex off;
                if ($request_method = options) {
                    add_header access-control-allow-origin '$http_origin' always;
                    add_header access-control-allow-credentials 'true' always;
                    add_header access-control-allow-methods 'get, post, put, patch, delete, options' always;
                    add_header access-control-allow-headers 'accept, authorization, cache-control, content-type, set-cookie, dnt, if-modified-since, keep-alive, origin, user-agent, x-mx-reqtoken, x-requested-with, x-sota-identity, x-internal-identity, x-csrftoken' always;
                    add_header access-control-max-age 1728000 always;
                    add_header content-length 0 always;
                    return 204;
                }
                add_header access-control-allow-origin '$http_origin' always;
                add_header access-control-allow-credentials 'true' always;
                add_header access-control-allow-methods 'get, post, put, patch, delete, options' always;
                add_header access-control-allow-headers 'accept, authorization, cache-control, content-type, set-cookie, dnt, if-modified-since, keep-alive, origin, user-agent, x-mx-reqtoken, x-requested-with, x-sota-identity, x-internal-identity, x-csrftoken' always;
            }

            location /health {
            return 200 'ok';
            add_header content-type text/plain;
            }

            #error_page  404              /404.html;

            # redirect server error pages to the static page /50x.html
            #
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }


