export const SET_MY_CAMPAIGNS_LIST_DATA = 'SET_MY_CAMPAIGNS_LIST_DATA';
export const SET_MY_CAMPAIGNS_LIST_LOADING = 'SET_MY_CAMPAIGNS_LIST_LOADING';
export const OMIT_ORDER_FROM_CAMPAIGN = 'OMIT_ORDER_FROM_CAMPAIGN';
export const OMIT_CAMPAIGN_FROM_LIST = 'OMIT_CAMPAIGN_FROM_LIST';

export const MY_CAMPAIGNS_LIST_PAGE_SIZE = 10;

export const MY_CAMPAIGNS_FILTER_FORM = 'MY_CAMPAIGNS_FILTER_FORM';
export const MY_CAMPAIGNS_DEFAULT_CHANNEL_TYPES = ['null', 0, 1, 2, 4, 6];
